# Generated by Django 4.2.7 on 2023-11-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
