# Generated by Django 4.2.6 on 2023-11-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0002_alter_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='invoice_class',
            field=models.CharField(choices=[('Resturant_Bill', 'Resturant'), ('Invoice', 'Invoice'), ('Hotel_Stay_Bill', 'Hotel'), ('Travel_Bill', 'Travel'), ('Fuel_Bill', 'Fuel')], default='Invoice', max_length=100),
        ),
    ]
