# Generated by Django 4.2.6 on 2023-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0003_remove_uploadedfile_title_uploadedfile_invoice_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='invoice_class',
            field=models.CharField(choices=[('Restaurant_Bill', 'Restaurant'), ('Invoice', 'Invoice'), ('Hotel_Stay_Bill', 'Hotel'), ('Travel_Bill', 'Travel'), ('Fuel_Bill', 'Fuel')], default='Invoice', max_length=100),
        ),
    ]
